Fix xgboost version conflict
antmicro/dl-in-iot-course pull request #2
Opened 2022-12-24 11:10 UTC by jdworzans

There is version conflict described in https://github.com/apache/tvm/issues/12009
Versions restriction as in https://github.com/apache/tvm/blob/main/python/gen_requirements.py#L279,
added to Apache TVM should eliminate this conflict.

2022-12-25 22:05 UTC, glatosinski requested changes
The code seems ok, please amend the commit so it sounds more like:

```
environments: Fixed xgboost version conflict
```

2022-12-28 16:41 UTC, jdworzans commented
> The code seems ok, please amend the commit so it sounds more like:
> 
> ```
> environments: Fixed xgboost version conflict
> ```

Ok, done

2022-12-28 17:38 UTC, glatosinski approved these changes
LGTM

2022-12-28 18:37 UTC, glatosinski commented
One small thing - we should wrap `xgboost>=1.1.0,<1.6.0` in quotas so the parser accepts this - I will apply it in the master branch.

2022-12-28 18:50 UTC, merged